// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
//
// NOTE: The Alert Engine has NO HTTP business API.
// It is a background scheduler that polls ClickHouse and fires notifications.
// This file documents its evaluation contract, Redis cooldown keys, and
// Kafka output schema for internal developer reference.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK",       "schema": {"$ref": "#/definitions/HealthResponse"}},
                    "503": {"description": "Degraded", "schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },
        "/metrics": {
            "get": {
                "tags": ["system"],
                "summary": "Prometheus metrics",
                "operationId": "metrics",
                "description": "Key metrics: alert_engine_rules_evaluated_total, alert_engine_rules_fired_total, alert_engine_clickhouse_query_errors_total, alert_engine_cooldown_skips_total, alert_engine_evaluation_duration_seconds.",
                "produces": ["text/plain"],
                "responses": {
                    "200": {"description": "Prometheus text format metrics"}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "enum": ["ok","degraded"], "example": "ok"},
                "service": {"type": "string", "example": "alertengine"}
            }
        },
        "AlertRule": {
            "description": "Loaded from PostgreSQL every 60 seconds. Only active=true rules are evaluated.",
            "type": "object",
            "properties": {
                "id":          {"type": "string",  "example": "alrt_9x2m1z"},
                "app_id":      {"type": "string",  "example": "app_abc123"},
                "name":        {"type": "string",  "example": "Low DAU Alert"},
                "metric_name": {"type": "string",  "enum": ["event_count","error_rate","dau"],
                                "example": "dau",
                                "description": "Determines the ClickHouse query template used"},
                "condition":   {"type": "string",  "enum": ["gt","lt","eq"], "example": "lt"},
                "threshold":   {"type": "number",  "format": "double", "example": 50000},
                "window_mins": {"type": "integer", "example": 60,
                                "description": "Lookback window for the ClickHouse query"},
                "channels":    {"type": "array",   "items": {"type": "string"},
                                "example": ["email","webhook"]},
                "webhook_url": {"type": "string",  "example": "https://hooks.example.com/pulse"},
                "email_to":    {"type": "array",   "items": {"type": "string"}, "example": ["oncall@acme.io"]},
                "active":      {"type": "boolean", "example": true}
            }
        },
        "NotificationMessage": {
            "description": "Produced to Kafka topic: notifications when an alert fires and is not in cooldown.",
            "type": "object",
            "properties": {
                "alert_id":     {"type": "string",  "example": "alrt_9x2m1z"},
                "app_id":       {"type": "string",  "example": "app_abc123"},
                "alert_name":   {"type": "string",  "example": "Low DAU Alert"},
                "metric_name":  {"type": "string",  "example": "dau"},
                "condition":    {"type": "string",  "example": "lt"},
                "threshold":    {"type": "number",  "format": "double", "example": 50000},
                "actual_value": {"type": "number",  "format": "double", "example": 43200,
                                 "description": "The metric value that triggered the alert"},
                "fired_at_ms":  {"type": "integer", "format": "int64",  "example": 1712345678000},
                "channels":     {"type": "array",   "items": {"type": "string"}, "example": ["email"]},
                "webhook_url":  {"type": "string"},
                "email_to":     {"type": "array",   "items": {"type": "string"}}
            }
        }
    },
    "tags": [
        {
            "name": "system",
            "description": "Health and Prometheus metrics. Alert Engine has no business HTTP API."
        }
    ],
    "x-kafka-interface": {
        "produces": [
            {
                "topic": "notifications",
                "key": "alert_id",
                "value_schema": "NotificationMessage (JSON)",
                "description": "Fired when an alert rule condition is met and the rule is not in its 30-minute cooldown window. Consumed by the Notification Service for webhook/email dispatch."
            }
        ]
    },
    "x-redis-keys": {
        "cooldown": {
            "key_pattern": "alert_cooldown:{alert_id}",
            "type": "string (SET with EX)",
            "ttl": "30 minutes",
            "description": "Set when an alert fires. Prevents the same alert from firing again within 30 minutes. Checked before producing to notifications topic."
        }
    },
    "x-evaluation-contract": {
        "schedule": "Every 60 seconds (ticker-based, not cron)",
        "rule_reload": "PostgreSQL query at the start of each evaluation cycle — no hot-reload interval, always fresh",
        "per_rule_flow": [
            "1. Build ClickHouse SQL using metric_name template + app_id + window_mins",
            "2. Execute query with 30-second timeout",
            "3. Compare result against threshold using condition operator (gt/lt/eq)",
            "4. If condition met: check Redis cooldown key alert_cooldown:{alert_id}",
            "5. If not in cooldown: publish NotificationMessage to notifications topic, SET cooldown key (EX 1800)"
        ],
        "clickhouse_query_templates": {
            "event_count": "SELECT count() FROM events WHERE app_id=? AND event_time >= now() - INTERVAL ? MINUTE",
            "dau":         "SELECT uniqHLL12(user_id) FROM events WHERE app_id=? AND event_time >= now() - INTERVAL ? MINUTE",
            "error_rate":  "SELECT countIf(event_name='error') / count() FROM events WHERE app_id=? AND event_time >= now() - INTERVAL ? MINUTE"
        },
        "failure_handling": "ClickHouse query errors are logged and counted in Prometheus. The rule is skipped for this cycle — no false alerts.",
        "deployment": "Single pod with Kubernetes restartPolicy=Always. Alert delay on crash = pod restart time (~30s). Redis cooldown survives restarts, preventing double-fire."
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:9095",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "PulseAnalytics — Alert Engine (Internal)",
	Description:      "Background scheduler service. Reloads alert rules from PostgreSQL every 60 seconds, evaluates each active rule against ClickHouse, and publishes NotificationMessages to the notifications Kafka topic when conditions are met. Includes a 30-minute per-alert Redis cooldown to prevent alert spam. No business HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
