version: "3.9"

services:
  chwriter:
    build:
      context: ..
      dockerfile: chwriter/Dockerfile
    ports:
      - "8088:8088"
      - "9097:9097"
    environment:
      CONFIG_PATH: /configs/config.yaml
    depends_on:
      - kafka
      - clickhouse
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:24
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  clickhouse_data:
