// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },
        "/v1/campaigns": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a new notification campaign. The campaign is inactive by default until explicitly started. The service subscribes to agg-results and session-events Kafka topics and evaluates active campaigns against each matching event. Supported channels: webhook, email (SMTP), push (FCM).",
                "tags": ["campaigns"],
                "summary": "Create campaign",
                "operationId": "createCampaign",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/CampaignRequest"}
                    }
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/Campaign"}},
                    "400": {"description": "Bad Request",    "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized",   "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/campaigns/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns campaign definition and current status.",
                "tags": ["campaigns"],
                "summary": "Get campaign",
                "operationId": "getCampaign",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string", "description": "Campaign ID"}
                ],
                "responses": {
                    "200": {"description": "OK",        "schema": {"$ref": "#/definitions/Campaign"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Updates campaign definition. Changes take effect on the next event evaluation cycle. Cannot update a concluded campaign.",
                "tags": ["campaigns"],
                "summary": "Update campaign",
                "operationId": "updateCampaign",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/CampaignRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/Campaign"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized","schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found",   "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/campaigns/{id}/pause": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Pauses event evaluation for the campaign. In-flight notifications already queued in Kafka will still be delivered.",
                "tags": ["campaigns"],
                "summary": "Pause campaign",
                "operationId": "pauseCampaign",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/StatusResponse"}},
                    "401": {"description": "Unauthorized","schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found",   "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/campaigns/{id}/resume": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Resumes event evaluation for a paused campaign.",
                "tags": ["campaigns"],
                "summary": "Resume campaign",
                "operationId": "resumeCampaign",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/StatusResponse"}},
                    "401": {"description": "Unauthorized","schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found",   "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/campaigns/{id}/stats": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns delivery statistics for the campaign: sent, delivered, failed counts plus open and click rates.",
                "tags": ["campaigns"],
                "summary": "Campaign delivery statistics",
                "operationId": "campaignStats",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK",        "schema": {"$ref": "#/definitions/CampaignStats"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "example": "ok"},
                "service": {"type": "string", "example": "notificationservice"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string", "example": "campaign not found"}
            }
        },
        "StatusResponse": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "enum": ["active","paused","concluded"], "example": "paused"}
            }
        },
        "CampaignRequest": {
            "type": "object",
            "required": ["app_id", "name", "trigger_type", "channel"],
            "properties": {
                "app_id":       {"type": "string", "example": "app_abc123"},
                "name":         {"type": "string", "example": "Win-Back Campaign"},
                "trigger_type": {
                    "type": "string",
                    "description": "Event name that triggers this campaign (e.g. session_end, purchase_completed)",
                    "example": "session_end"
                },
                "trigger_conf": {
                    "type": "object",
                    "additionalProperties": {"type": "string"},
                    "description": "Optional trigger conditions as key-value filters on event properties",
                    "example": {"inactivity_days": "7", "country": "US"}
                },
                "channel": {
                    "type": "string",
                    "enum": ["webhook", "email", "push"],
                    "example": "email"
                },
                "channel_conf": {
                    "type": "object",
                    "additionalProperties": {"type": "string"},
                    "description": "Channel-specific config. webhook: {url, secret}. email: {to, subject, template_id}. push: {fcm_topic}.",
                    "example": {"to": "user@example.com", "subject": "We miss you!", "template_id": "tmpl_winback"}
                }
            }
        },
        "Campaign": {
            "type": "object",
            "properties": {
                "id":           {"type": "string",  "example": "cmp_8f3k2z"},
                "app_id":       {"type": "string",  "example": "app_abc123"},
                "name":         {"type": "string",  "example": "Win-Back Campaign"},
                "trigger_type": {"type": "string",  "example": "session_end"},
                "trigger_conf": {
                    "type": "object",
                    "additionalProperties": {"type": "string"}
                },
                "channel":      {"type": "string",  "enum": ["webhook","email","push"], "example": "email"},
                "channel_conf": {
                    "type": "object",
                    "additionalProperties": {"type": "string"}
                },
                "active":       {"type": "boolean", "example": true},
                "created_at":   {"type": "string",  "format": "date-time", "example": "2026-04-12T10:00:00Z"}
            }
        },
        "CampaignStats": {
            "type": "object",
            "properties": {
                "campaign_id": {"type": "string",  "example": "cmp_8f3k2z"},
                "sent":        {"type": "integer", "format": "int64", "example": 142000,
                                "description": "Total notifications dispatched"},
                "delivered":   {"type": "integer", "format": "int64", "example": 138500,
                                "description": "Confirmed successful deliveries"},
                "failed":      {"type": "integer", "format": "int64", "example": 3500,
                                "description": "Delivery failures after 3 retries"},
                "open_rate":   {"type": "number",  "format": "double", "example": 0.24,
                                "description": "Fraction of delivered notifications opened (push/email only)"},
                "click_rate":  {"type": "number",  "format": "double", "example": 0.08,
                                "description": "Fraction of delivered notifications clicked (push/email only)"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT bearer token. Obtain from POST /v1/auth/token on the Auth Service.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {"name": "campaigns", "description": "Campaign lifecycle management — create, update, pause, resume, stats"},
        {"name": "system",    "description": "Health and operational checks"}
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8084",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "PulseAnalytics — Notification Service API",
	Description:      "Campaign management and notification dispatch service. Consumes agg-results and session-events Kafka topics, evaluates active campaigns against each event, and dispatches via webhook, SMTP email, or Firebase push (FCM). Includes a 30-minute per-user cooldown to prevent notification spam.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
