// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {

        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },

        "/v1/auth/login": {
            "post": {
                "description": "Exchanges an API key for a JWT. Convenience endpoint co-located on the Query API; proxies to the Auth Service internally.",
                "tags": ["auth"],
                "summary": "Exchange API key for JWT",
                "operationId": "authLogin",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/LoginRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",           "schema": {"$ref": "#/definitions/LoginResponse"}},
                    "401": {"description": "Invalid key",  "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/events/count": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns event counts over time with optional grouping. Uses ClickHouse Materialized Views for sub-100ms response on large datasets.",
                "tags": ["analytics"],
                "summary": "Event count over time",
                "operationId": "eventCount",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id",      "in": "query", "required": true,  "type": "string",  "description": "Application ID"},
                    {"name": "event_name",  "in": "query", "required": false, "type": "string",  "description": "Filter to specific event (omit for all events)"},
                    {"name": "from_ms",     "in": "query", "required": false, "type": "integer", "format": "int64", "description": "Start time epoch ms (default: 30 days ago)"},
                    {"name": "to_ms",       "in": "query", "required": false, "type": "integer", "format": "int64", "description": "End time epoch ms (default: now)"},
                    {"name": "granularity", "in": "query", "required": false, "type": "string",  "enum": ["minute","hour","day","week","month"], "default": "day"}
                ],
                "responses": {
                    "200": {"description": "OK",           "schema": {"$ref": "#/definitions/EventCountResponse"}},
                    "400": {"description": "Bad Request",  "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Error","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/events/breakdown": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Breaks down an event count by a specific property value (e.g. plan, country, platform). Returns the top-N property values by count over the specified time range.",
                "tags": ["analytics"],
                "summary": "Event count breakdown by property",
                "operationId": "eventBreakdown",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/BreakdownRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"type": "array", "items": {"$ref": "#/definitions/BreakdownPoint"}}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/funnels/query": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Computes step-by-step funnel conversion rates using ClickHouse windowFunnel(). Runs in <200ms on 10B rows with partition pruning.",
                "tags": ["analytics"],
                "summary": "Funnel conversion analysis",
                "operationId": "funnelQuery",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/FunnelRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/FunnelResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/dau": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Daily, weekly, or monthly active users using HyperLogLog (uniqHLL12) for approximate counting at massive scale. Error margin ~1.6%.",
                "tags": ["analytics"],
                "summary": "Active users (DAU / WAU / MAU)",
                "operationId": "dau",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id",      "in": "query", "required": true,  "type": "string"},
                    {"name": "from_ms",     "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "to_ms",       "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "granularity", "in": "query", "required": false, "type": "string", "enum": ["day","week","month"], "default": "day"}
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/EventCountResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/retention": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Day-N retention cohort analysis. Returns % of users who installed on day 0 and returned on day N for each install cohort.",
                "tags": ["analytics"],
                "summary": "Day-N retention cohorts",
                "operationId": "retention",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/RetentionRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/RetentionResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/sessions/metrics": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Aggregated session metrics: average duration, median duration, total sessions, and average events per session.",
                "tags": ["analytics"],
                "summary": "Session metrics",
                "operationId": "sessionMetrics",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id",  "in": "query", "required": true,  "type": "string"},
                    {"name": "from_ms", "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "to_ms",   "in": "query", "required": false, "type": "integer", "format": "int64"}
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/SessionMetricsResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/realtime": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns events-per-minute rate and unique active users from the last 5 minutes. Backed by a ClickHouse query on the hot partition — not cached, so use sparingly (dashboard refresh ≥ 10s recommended).",
                "tags": ["analytics"],
                "summary": "Real-time activity (last 5 minutes)",
                "operationId": "realtime",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id", "in": "query", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/RealTimeStats"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/paths": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "User-journey path analysis. Returns the top-N event sequences starting from (or ending at) an anchor event. Useful for discovering navigation patterns and drop-off points.",
                "tags": ["analytics"],
                "summary": "User journey path analysis",
                "operationId": "paths",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/PathRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/PathResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/revenue": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Transaction revenue metrics over time: total revenue, transaction count, unique payors, ARPU (average revenue per user), and ARPPU (average revenue per paying user).",
                "tags": ["analytics"],
                "summary": "Revenue metrics",
                "operationId": "revenue",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id",        "in": "query", "required": true,  "type": "string"},
                    {"name": "from_ms",        "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "to_ms",          "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "granularity",    "in": "query", "required": false, "type": "string", "enum": ["day","week","month"], "default": "day"},
                    {"name": "revenue_event",  "in": "query", "required": false, "type": "string", "default": "purchase", "description": "Event name that carries the revenue property"},
                    {"name": "revenue_prop",   "in": "query", "required": false, "type": "string", "default": "revenue",  "description": "Event property name containing the numeric revenue amount"},
                    {"name": "currency_prop",  "in": "query", "required": false, "type": "string", "description": "Event property name for currency code (optional)"}
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/RevenueResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/ltv": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Install-cohort LTV analysis. Groups users by install date and computes cumulative revenue per user at each day interval (e.g. Day 1, Day 7, Day 30). Useful for UA payback period analysis.",
                "tags": ["analytics"],
                "summary": "Cohort LTV analysis",
                "operationId": "ltv",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/LTVCohortRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"type": "array", "items": {"$ref": "#/definitions/LTVCohortPoint"}}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/attribution": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "UTM-based attribution analysis. Counts users, conversions, and revenue by utm_source / utm_medium / utm_campaign using first-touch, last-touch, or linear attribution models.",
                "tags": ["analytics"],
                "summary": "Attribution analysis",
                "operationId": "attribution",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id",      "in": "query", "required": true,  "type": "string"},
                    {"name": "from_ms",     "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "to_ms",       "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "model",       "in": "query", "required": false, "type": "string", "enum": ["first_touch","last_touch","linear"], "default": "last_touch"},
                    {"name": "granularity", "in": "query", "required": false, "type": "string", "enum": ["day","week","month"], "default": "day"}
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"type": "array", "items": {"$ref": "#/definitions/AttributionPoint"}}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/segments/count": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Counts users matching a dynamic segment definition. Evaluates property filters and event-membership conditions against the ClickHouse events table. Max evaluation window: 90 days.",
                "tags": ["analytics"],
                "summary": "Dynamic segment user count",
                "operationId": "segmentCount",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/SegmentCountRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/SegmentCountResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/users/{user_id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns aggregated profile for a single user: first/last seen, total events, total sessions, total revenue, geo, and merged user traits from Identify calls.",
                "tags": ["users"],
                "summary": "User profile",
                "operationId": "userProfile",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "user_id", "in": "path",  "required": true,  "type": "string"},
                    {"name": "app_id",  "in": "query", "required": true,  "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK",        "schema": {"$ref": "#/definitions/UserProfileResponse"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "User not found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/users/{user_id}/events": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns the raw event timeline for a user, ordered by event_time descending. Maximum 500 events returned. Use from_ms / to_ms to paginate over long histories.",
                "tags": ["users"],
                "summary": "User event timeline",
                "operationId": "userTimeline",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "user_id",    "in": "path",  "required": true,  "type": "string"},
                    {"name": "app_id",     "in": "query", "required": true,  "type": "string"},
                    {"name": "from_ms",    "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "to_ms",      "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "event_name", "in": "query", "required": false, "type": "string",  "description": "Filter to a specific event name"}
                ],
                "responses": {
                    "200": {"description": "OK",         "schema": {"type": "array", "items": {"$ref": "#/definitions/UserEvent"}}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/experiments/{id}/results": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns per-variant conversion rate, revenue, and statistical significance (p-value) for the experiment. Variants are compared against the control variant.",
                "tags": ["experiments"],
                "summary": "Experiment results",
                "operationId": "experimentResults",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id",      "in": "path",  "required": true,  "type": "string", "description": "Experiment ID"},
                    {"name": "app_id",  "in": "query", "required": true,  "type": "string"},
                    {"name": "from_ms", "in": "query", "required": false, "type": "integer", "format": "int64"},
                    {"name": "to_ms",   "in": "query", "required": false, "type": "integer", "format": "int64"}
                ],
                "responses": {
                    "200": {"description": "OK",        "schema": {"$ref": "#/definitions/ExperimentResult"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/funnels": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a named funnel definition with ordered steps and a conversion time window.",
                "tags": ["funnels"],
                "summary": "Create funnel definition",
                "operationId": "createFunnel",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/CreateFunnelRequest"}
                    }
                ],
                "responses": {
                    "201": {"description": "Created",    "schema": {"$ref": "#/definitions/CreateFunnelResponse"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/funnels/{app_id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Lists all funnel definitions for the given application.",
                "tags": ["funnels"],
                "summary": "List funnel definitions",
                "operationId": "listFunnels",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/FunnelDefinition"}}}
                }
            }
        },

        "/v1/apps": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Lists all apps belonging to the authenticated organisation.",
                "tags": ["management"],
                "summary": "List apps",
                "operationId": "listApps",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/App"}}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a new app under the authenticated organisation and provisions an API key.",
                "tags": ["management"],
                "summary": "Create app",
                "operationId": "createApp",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/CreateAppRequest"}
                    }
                ],
                "responses": {
                    "201": {"description": "Created",    "schema": {"$ref": "#/definitions/App"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/apps/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Updates app name or rate-limit settings (RPS and burst).",
                "tags": ["management"],
                "summary": "Update app",
                "operationId": "updateApp",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/UpdateAppRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/IDStatusResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found",   "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Soft-deletes the app. The API key is immediately invalidated.",
                "tags": ["management"],
                "summary": "Delete app",
                "operationId": "deleteApp",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "404": {"description": "Not Found",   "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/apps/{id}/rotate-key": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Rotates the API key for the specified app. The old key is immediately invalidated.",
                "tags": ["management"],
                "summary": "Rotate app API key",
                "operationId": "rotateAppAPIKey",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK",         "schema": {"$ref": "#/definitions/RotateKeyResponse"}},
                    "404": {"description": "Not Found",  "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/alerts": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Lists alert rules for the given application.",
                "tags": ["management"],
                "summary": "List alert rules",
                "operationId": "listAlerts",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id", "in": "query", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/AlertRule"}}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a new threshold-based alert rule. The Alert Engine evaluates active rules against ClickHouse every 60 seconds and fires when the condition is met.",
                "tags": ["management"],
                "summary": "Create alert rule",
                "operationId": "createAlert",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/AlertRule"}
                    }
                ],
                "responses": {
                    "201": {"description": "Created",    "schema": {"$ref": "#/definitions/AlertRule"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/alerts/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Updates an existing alert rule.",
                "tags": ["management"],
                "summary": "Update alert rule",
                "operationId": "updateAlert",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/AlertRule"}}
                ],
                "responses": {
                    "200": {"description": "OK",         "schema": {"$ref": "#/definitions/IDStatusResponse"}},
                    "404": {"description": "Not Found",  "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Deletes an alert rule.",
                "tags": ["management"],
                "summary": "Delete alert rule",
                "operationId": "deleteAlert",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/cohorts": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Lists cohort definitions for the given application.",
                "tags": ["management"],
                "summary": "List cohorts",
                "operationId": "listCohorts",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id", "in": "query", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/CohortDefinition"}}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a named cohort from a ClickHouse SQL filter expression.",
                "tags": ["management"],
                "summary": "Create cohort",
                "operationId": "createCohort",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CohortDefinition"}}
                ],
                "responses": {
                    "201": {"description": "Created",    "schema": {"$ref": "#/definitions/CohortDefinition"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/cohorts/{id}": {
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Deletes a cohort definition.",
                "tags": ["management"],
                "summary": "Delete cohort",
                "operationId": "deleteCohort",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/experiments": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Lists A/B experiments for the given application.",
                "tags": ["experiments"],
                "summary": "List experiments",
                "operationId": "listExperiments",
                "produces": ["application/json"],
                "parameters": [
                    {"name": "app_id", "in": "query", "required": true, "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/Experiment"}}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a new A/B experiment with named variants.",
                "tags": ["experiments"],
                "summary": "Create experiment",
                "operationId": "createExperiment",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/Experiment"}}
                ],
                "responses": {
                    "201": {"description": "Created",    "schema": {"$ref": "#/definitions/Experiment"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/experiments/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Updates experiment metadata or status (draft → running → paused → concluded).",
                "tags": ["experiments"],
                "summary": "Update experiment",
                "operationId": "updateExperiment",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/Experiment"}}
                ],
                "responses": {
                    "200": {"description": "OK",         "schema": {"$ref": "#/definitions/IDStatusResponse"}},
                    "404": {"description": "Not Found",  "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Deletes an experiment. Only draft experiments can be deleted.",
                "tags": ["experiments"],
                "summary": "Delete experiment",
                "operationId": "deleteExperiment",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "409": {"description": "Cannot delete non-draft experiment", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/orgs": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns the organisation details for the authenticated token.",
                "tags": ["management"],
                "summary": "Get organisation",
                "operationId": "getOrg",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/Org"}}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a new organisation. Typically only called by super-admin or the Auth Service register flow.",
                "tags": ["management"],
                "summary": "Create organisation",
                "operationId": "createOrg",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/Org"}}
                ],
                "responses": {
                    "201": {"description": "Created",    "schema": {"$ref": "#/definitions/Org"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },

        "/v1/orgs/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Updates organisation name or plan.",
                "tags": ["management"],
                "summary": "Update organisation",
                "operationId": "updateOrg",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {"name": "id",   "in": "path", "required": true, "type": "string"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/Org"}}
                ],
                "responses": {
                    "200": {"description": "OK",         "schema": {"$ref": "#/definitions/IDStatusResponse"}},
                    "404": {"description": "Not Found",  "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        }

    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "example": "ok"},
                "service": {"type": "string", "example": "queryapi"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string", "example": "app_id required"}
            }
        },
        "IDStatusResponse": {
            "type": "object",
            "properties": {
                "id":     {"type": "string", "example": "app_abc123"},
                "status": {"type": "string", "example": "updated"}
            }
        },
        "LoginRequest": {
            "type": "object",
            "required": ["api_key"],
            "properties": {
                "api_key": {"type": "string", "example": "pk_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
            }
        },
        "LoginResponse": {
            "type": "object",
            "properties": {
                "token":   {"type": "string",  "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."},
                "app_id":  {"type": "string",  "example": "app_abc123"},
                "org_id":  {"type": "string",  "example": "org_7f3k2m"},
                "expires": {"type": "string",  "format": "date-time", "example": "2026-04-13T12:00:00Z"}
            }
        },
        "DataPoint": {
            "type": "object",
            "properties": {
                "timestamp_ms": {"type": "integer", "format": "int64", "example": 1712304000000},
                "value":        {"type": "number",  "format": "double", "example": 142500},
                "dimensions":   {"type": "object",  "additionalProperties": {"type": "string"}}
            }
        },
        "EventCountResponse": {
            "type": "object",
            "properties": {
                "points": {"type": "array", "items": {"$ref": "#/definitions/DataPoint"}},
                "total":  {"type": "integer", "format": "int64", "example": 4275000}
            }
        },
        "Filter": {
            "type": "object",
            "required": ["property", "operator", "value"],
            "properties": {
                "property": {"type": "string", "example": "plan"},
                "operator": {"type": "string", "enum": ["eq","neq","contains"], "example": "eq"},
                "value":    {"type": "string", "example": "pro"}
            }
        },
        "FunnelRequest": {
            "type": "object",
            "required": ["app_id", "steps"],
            "properties": {
                "app_id":         {"type": "string", "example": "app_abc123"},
                "steps":          {"type": "array",  "items": {"type": "string"}, "minItems": 2, "maxItems": 10,
                                   "example": ["app_installed","user_registered","purchase_completed"]},
                "window_seconds": {"type": "integer","format": "int64", "default": 604800, "example": 604800,
                                   "description": "Max time allowed between first and last step (default 7 days)"},
                "from_ms":        {"type": "integer","format": "int64", "example": 1709596800000},
                "to_ms":          {"type": "integer","format": "int64", "example": 1712188800000}
            }
        },
        "FunnelStep": {
            "type": "object",
            "properties": {
                "event_name":      {"type": "string",  "example": "user_registered"},
                "user_count":      {"type": "integer", "format": "int64",  "example": 85000},
                "conversion_rate": {"type": "number",  "format": "double", "example": 0.85},
                "drop_off_rate":   {"type": "number",  "format": "double", "example": 0.15}
            }
        },
        "FunnelResponse": {
            "type": "object",
            "properties": {
                "steps": {"type": "array", "items": {"$ref": "#/definitions/FunnelStep"}}
            }
        },
        "RetentionRequest": {
            "type": "object",
            "required": ["app_id"],
            "properties": {
                "app_id":  {"type": "string",  "example": "app_abc123"},
                "from_ms": {"type": "integer", "format": "int64"},
                "to_ms":   {"type": "integer", "format": "int64"},
                "day_ns":  {"type": "array",   "items": {"type": "integer", "format": "int32"},
                            "default": [1, 3, 7, 14, 30]}
            }
        },
        "RetentionCohort": {
            "type": "object",
            "properties": {
                "install_date": {"type": "string", "format": "date", "example": "2024-04-01"},
                "cohort_size":  {"type": "integer","format": "int64", "example": 12500},
                "day_n_rates":  {
                    "type": "object",
                    "additionalProperties": {"type": "number", "format": "double"},
                    "example": {"day_1": 0.42, "day_3": 0.28, "day_7": 0.19, "day_14": 0.13, "day_30": 0.08}
                }
            }
        },
        "RetentionResponse": {
            "type": "object",
            "properties": {
                "cohorts": {"type": "array", "items": {"$ref": "#/definitions/RetentionCohort"}}
            }
        },
        "SessionMetricsResponse": {
            "type": "object",
            "properties": {
                "avg_session_duration_s":    {"type": "number", "format": "double", "example": 187.4},
                "median_session_duration_s": {"type": "number", "format": "double", "example": 142.0},
                "total_sessions":            {"type": "integer","format": "int64",  "example": 4200000},
                "avg_events_per_session":    {"type": "number", "format": "double", "example": 12.3}
            }
        },
        "RealTimeStats": {
            "type": "object",
            "properties": {
                "app_id":          {"type": "string",  "example": "app_abc123"},
                "as_of":           {"type": "string",  "format": "date-time", "example": "2026-04-12T10:00:00Z"},
                "events_per_min":  {"type": "number",  "format": "double", "example": 38420.5},
                "active_users":    {"type": "integer", "format": "int64",  "example": 5200,
                                    "description": "Unique users seen in last 5 minutes"},
                "top_events":      {"type": "array",   "items": {"$ref": "#/definitions/EventFreq"}}
            }
        },
        "EventFreq": {
            "type": "object",
            "properties": {
                "event_name": {"type": "string",  "example": "screen_view"},
                "count":      {"type": "integer", "format": "int64", "example": 182400}
            }
        },
        "PathRequest": {
            "type": "object",
            "required": ["app_id"],
            "properties": {
                "app_id":      {"type": "string",  "example": "app_abc123"},
                "start_event": {"type": "string",  "example": "app_opened",
                                "description": "Anchor event to start paths from (default: session_start)"},
                "end_event":   {"type": "string",  "example": "purchase_completed",
                                "description": "Optional anchor event to end paths at"},
                "max_steps":   {"type": "integer", "default": 5,  "example": 5,
                                "description": "Maximum path depth"},
                "top_n":       {"type": "integer", "default": 10, "example": 10,
                                "description": "Return top N paths by user count"},
                "from_ms":     {"type": "integer", "format": "int64"},
                "to_ms":       {"type": "integer", "format": "int64"},
                "filters":     {"type": "array",   "items": {"$ref": "#/definitions/Filter"}}
            }
        },
        "PathNode": {
            "type": "object",
            "properties": {
                "event_name": {"type": "string",  "example": "product_viewed"},
                "count":      {"type": "integer", "format": "int64",  "example": 42000},
                "percentage": {"type": "number",  "format": "double", "example": 0.31},
                "drop_off":   {"type": "number",  "format": "double", "example": 0.18}
            }
        },
        "PathResponse": {
            "type": "object",
            "properties": {
                "root_event":   {"type": "string",  "example": "app_opened"},
                "total_users":  {"type": "integer", "format": "int64", "example": 135000},
                "paths":        {"type": "array",   "items": {"type": "array", "items": {"$ref": "#/definitions/PathNode"}}}
            }
        },
        "RevenuePoint": {
            "type": "object",
            "properties": {
                "bucket":         {"type": "string",  "example": "2026-04-01"},
                "total_revenue":  {"type": "number",  "format": "double", "example": 48750.25},
                "tx_count":       {"type": "integer", "format": "int64",  "example": 1250},
                "unique_payors":  {"type": "integer", "format": "int64",  "example": 980},
                "arpu":           {"type": "number",  "format": "double", "example": 0.49,
                                   "description": "Total revenue / all DAU"},
                "arppu":          {"type": "number",  "format": "double", "example": 49.74,
                                   "description": "Total revenue / unique paying users"}
            }
        },
        "RevenueResponse": {
            "type": "object",
            "properties": {
                "app_id":    {"type": "string", "example": "app_abc123"},
                "currency":  {"type": "string", "example": "USD"},
                "total_ltv": {"type": "number", "format": "double", "example": 1425000.75},
                "points":    {"type": "array",  "items": {"$ref": "#/definitions/RevenuePoint"}}
            }
        },
        "LTVCohortRequest": {
            "type": "object",
            "required": ["app_id"],
            "properties": {
                "app_id":        {"type": "string", "example": "app_abc123"},
                "from_ms":       {"type": "integer","format": "int64"},
                "to_ms":         {"type": "integer","format": "int64"},
                "days":          {"type": "array",  "items": {"type": "integer"},
                                  "default": [1, 7, 14, 30, 60, 90], "example": [1,7,14,30,60,90]},
                "revenue_event": {"type": "string", "default": "purchase", "example": "purchase"},
                "revenue_prop":  {"type": "string", "default": "revenue",  "example": "revenue"}
            }
        },
        "LTVCohortPoint": {
            "type": "object",
            "properties": {
                "cohort_date": {"type": "string", "format": "date", "example": "2026-03-01"},
                "users":       {"type": "integer","format": "int64", "example": 8200},
                "ltv_by_day":  {
                    "type": "object",
                    "additionalProperties": {"type": "number", "format": "double"},
                    "example": {"day_1": 2.10, "day_7": 12.40, "day_30": 38.75, "day_90": 61.20}
                }
            }
        },
        "AttributionPoint": {
            "type": "object",
            "properties": {
                "bucket":          {"type": "string",  "example": "2026-04-01"},
                "source":          {"type": "string",  "example": "google"},
                "medium":          {"type": "string",  "example": "cpc"},
                "campaign":        {"type": "string",  "example": "spring_sale_2026"},
                "users":           {"type": "integer", "format": "int64",  "example": 4800},
                "conversions":     {"type": "integer", "format": "int64",  "example": 384},
                "revenue":         {"type": "number",  "format": "double", "example": 18240.50},
                "conversion_pct":  {"type": "number",  "format": "double", "example": 0.08}
            }
        },
        "BreakdownRequest": {
            "type": "object",
            "required": ["app_id", "event_name", "property"],
            "properties": {
                "app_id":      {"type": "string",  "example": "app_abc123"},
                "event_name":  {"type": "string",  "example": "purchase_completed"},
                "property":    {"type": "string",  "example": "plan",
                                "description": "Event or user property to group by"},
                "from_ms":     {"type": "integer", "format": "int64"},
                "to_ms":       {"type": "integer", "format": "int64"},
                "granularity": {"type": "string",  "enum": ["day","week","month"], "default": "day"},
                "top_n":       {"type": "integer", "default": 20, "example": 20}
            }
        },
        "BreakdownPoint": {
            "type": "object",
            "properties": {
                "bucket":          {"type": "string",  "example": "2026-04-01"},
                "property_value":  {"type": "string",  "example": "pro"},
                "count":           {"type": "integer", "format": "int64",  "example": 8400},
                "unique_users":    {"type": "integer", "format": "int64",  "example": 3200},
                "percentage":      {"type": "number",  "format": "double", "example": 0.42}
            }
        },
        "SegmentCountRequest": {
            "type": "object",
            "required": ["app_id"],
            "properties": {
                "app_id":     {"type": "string", "example": "app_abc123"},
                "filters":    {"type": "array",  "items": {"$ref": "#/definitions/Filter"},
                               "description": "Property filters applied to user traits or event properties"},
                "has_events": {"type": "array",  "items": {"type": "string"},
                               "example": ["purchase_completed", "subscription_started"],
                               "description": "Users must have performed ALL listed events within the window"},
                "from_ms":    {"type": "integer","format": "int64"},
                "to_ms":      {"type": "integer","format": "int64"}
            }
        },
        "SegmentCountResponse": {
            "type": "object",
            "properties": {
                "app_id":         {"type": "string",  "example": "app_abc123"},
                "matched_users":  {"type": "integer", "format": "int64",  "example": 42800},
                "evaluated_at":   {"type": "string",  "format": "date-time", "example": "2026-04-12T10:00:00Z"}
            }
        },
        "UserProfileResponse": {
            "type": "object",
            "properties": {
                "app_id":         {"type": "string",  "example": "app_abc123"},
                "user_id":        {"type": "string",  "example": "usr_xyz"},
                "first_seen":     {"type": "string",  "format": "date-time"},
                "last_seen":      {"type": "string",  "format": "date-time"},
                "total_events":   {"type": "integer", "format": "int64",  "example": 2840},
                "total_sessions": {"type": "integer", "format": "int64",  "example": 47},
                "total_revenue":  {"type": "number",  "format": "double", "example": 149.97},
                "country":        {"type": "string",  "example": "US"},
                "city":           {"type": "string",  "example": "San Francisco"},
                "properties":     {"type": "object",  "additionalProperties": {"type": "string"},
                                   "example": {"email": "alice@example.com", "plan": "pro"}},
                "top_events":     {"type": "array",   "items": {"$ref": "#/definitions/EventFreq"}}
            }
        },
        "UserEvent": {
            "type": "object",
            "properties": {
                "event_name":  {"type": "string", "example": "product_viewed"},
                "event_time":  {"type": "string", "format": "date-time"},
                "session_id":  {"type": "string", "example": "sess_8f3k2z"},
                "country":     {"type": "string", "example": "US"},
                "props":       {"type": "object", "additionalProperties": {"type": "string"}}
            }
        },
        "ExperimentResult": {
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "example": "exp_m3n4p5"},
                "metric":        {"type": "string", "example": "purchase_completed"},
                "variants":      {"type": "array",  "items": {"$ref": "#/definitions/VariantResult"}}
            }
        },
        "VariantResult": {
            "type": "object",
            "properties": {
                "variant":        {"type": "string",  "example": "treatment_a"},
                "users":          {"type": "integer", "format": "int64",  "example": 18500},
                "conversions":    {"type": "integer", "format": "int64",  "example": 1480},
                "conversion_pct": {"type": "number",  "format": "double", "example": 0.08,
                                   "description": "Conversion rate for this variant"},
                "revenue":        {"type": "number",  "format": "double", "example": 74000},
                "lift_pct":       {"type": "number",  "format": "double", "example": 0.12,
                                   "description": "Relative lift over control variant"},
                "p_value":        {"type": "number",  "format": "double", "example": 0.032,
                                   "description": "Statistical significance (two-tailed z-test)"}
            }
        },
        "CreateFunnelRequest": {
            "type": "object",
            "required": ["app_id", "name", "steps"],
            "properties": {
                "app_id":         {"type": "string", "example": "app_abc123"},
                "name":           {"type": "string", "example": "Onboarding Funnel"},
                "steps":          {"type": "array",  "items": {"type": "string"},
                                   "example": ["app_installed","user_registered","purchase_completed"]},
                "window_seconds": {"type": "integer","format": "int64", "default": 604800}
            }
        },
        "CreateFunnelResponse": {
            "type": "object",
            "properties": {
                "funnel_id": {"type": "string", "example": "f-1712345678000000000"}
            }
        },
        "FunnelDefinition": {
            "type": "object",
            "properties": {
                "funnel_id":      {"type": "string"},
                "app_id":         {"type": "string"},
                "name":           {"type": "string"},
                "steps":          {"type": "array", "items": {"type": "string"}},
                "window_seconds": {"type": "integer","format": "int64"},
                "created_at":     {"type": "string", "format": "date-time"}
            }
        },
        "App": {
            "type": "object",
            "properties": {
                "id":         {"type": "string",  "example": "app_abc123"},
                "org_id":     {"type": "string",  "example": "org_7f3k2m"},
                "name":       {"type": "string",  "example": "Acme iOS"},
                "api_key":    {"type": "string",  "example": "pk_live_xxxxxxxxxxxxxxxx"},
                "rps":        {"type": "number",  "format": "double", "example": 10000,
                               "description": "Rate limit: sustained events per second"},
                "burst":      {"type": "integer", "example": 50000,
                               "description": "Rate limit: burst capacity above RPS"},
                "active":     {"type": "boolean", "example": true},
                "created_at": {"type": "string",  "format": "date-time"}
            }
        },
        "CreateAppRequest": {
            "type": "object",
            "required": ["org_id", "name"],
            "properties": {
                "org_id": {"type": "string", "example": "org_7f3k2m"},
                "name":   {"type": "string", "example": "Acme Android"}
            }
        },
        "UpdateAppRequest": {
            "type": "object",
            "properties": {
                "name":  {"type": "string",  "example": "Acme Android v2"},
                "rps":   {"type": "number",  "format": "double", "example": 20000},
                "burst": {"type": "integer", "example": 100000}
            }
        },
        "RotateKeyResponse": {
            "type": "object",
            "properties": {
                "app_id":  {"type": "string", "example": "app_abc123"},
                "api_key": {"type": "string", "example": "pk_live_yyyyyyyyyyyyyyyyyyyyyyyy"}
            }
        },
        "AlertRule": {
            "type": "object",
            "required": ["app_id", "name", "metric_name", "condition", "threshold"],
            "properties": {
                "id":           {"type": "string",  "example": "alrt_9x2m1z"},
                "app_id":       {"type": "string",  "example": "app_abc123"},
                "name":         {"type": "string",  "example": "Low DAU Alert"},
                "metric_name":  {"type": "string",  "enum": ["event_count","error_rate","dau"],
                                 "example": "dau"},
                "condition":    {"type": "string",  "enum": ["gt","lt","eq"], "example": "lt"},
                "threshold":    {"type": "number",  "format": "double", "example": 50000},
                "window_mins":  {"type": "integer", "example": 60,
                                 "description": "Evaluation window in minutes"},
                "channels":     {"type": "array",   "items": {"type": "string"},
                                 "example": ["email","webhook"]},
                "webhook_url":  {"type": "string",  "example": "https://hooks.example.com/pulse"},
                "email_to":     {"type": "array",   "items": {"type": "string"},
                                 "example": ["oncall@acme.io"]},
                "active":       {"type": "boolean", "example": true},
                "created_at":   {"type": "string",  "format": "date-time"}
            }
        },
        "CohortDefinition": {
            "type": "object",
            "required": ["app_id", "name"],
            "properties": {
                "id":          {"type": "string", "example": "coh_4x7k9m"},
                "app_id":      {"type": "string", "example": "app_abc123"},
                "name":        {"type": "string", "example": "Power Users"},
                "description": {"type": "string", "example": "Users with > 50 sessions in 30 days"},
                "filter_sql":  {"type": "string", "example": "session_count > 50",
                                "description": "ClickHouse WHERE clause expression applied to user aggregates"},
                "user_count":  {"type": "integer","format": "int64", "example": 14200},
                "created_at":  {"type": "string", "format": "date-time"}
            }
        },
        "Experiment": {
            "type": "object",
            "required": ["app_id", "name", "goal_event"],
            "properties": {
                "id":          {"type": "string",  "example": "exp_m3n4p5"},
                "app_id":      {"type": "string",  "example": "app_abc123"},
                "name":        {"type": "string",  "example": "Checkout Button Colour"},
                "description": {"type": "string",  "example": "Test green vs blue CTA button"},
                "status":      {"type": "string",  "enum": ["draft","running","paused","concluded"],
                                "example": "running"},
                "goal_event":  {"type": "string",  "example": "purchase_completed"},
                "variants":    {"type": "object",  "description": "Map of variant name → traffic split",
                                "example": {"control": 0.5, "treatment_a": 0.5}},
                "start_at":    {"type": "string",  "format": "date-time"},
                "end_at":      {"type": "string",  "format": "date-time"},
                "created_at":  {"type": "string",  "format": "date-time"}
            }
        },
        "Org": {
            "type": "object",
            "required": ["name"],
            "properties": {
                "id":         {"type": "string", "example": "org_7f3k2m"},
                "name":       {"type": "string", "example": "Acme Corp"},
                "plan":       {"type": "string", "enum": ["free","growth","enterprise"], "example": "growth"},
                "created_at": {"type": "string", "format": "date-time"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT bearer token. Obtain from POST /v1/auth/login or POST /v1/auth/token on the Auth Service.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {"name": "auth",        "description": "Token exchange (convenience endpoint)"},
        {"name": "analytics",   "description": "Core analytics queries — events, funnels, DAU, retention, sessions, paths, revenue, attribution, breakdown, realtime, segments"},
        {"name": "users",       "description": "Per-user profile and event timeline"},
        {"name": "funnels",     "description": "Funnel definition CRUD"},
        {"name": "experiments", "description": "A/B experiment CRUD and results"},
        {"name": "management",  "description": "Organisation, app, alert, and cohort management"},
        {"name": "system",      "description": "Health and operational checks"}
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "PulseAnalytics — Query API",
	Description:      "Analytics query service for funnels, retention, DAU/WAU/MAU, session metrics, event counts, paths, revenue, LTV, attribution, experiments, and user profiles. Backed by ClickHouse with 3-tier caching (L1 in-process → L2 Redis 5-min TTL → L3 ClickHouse query_cache). All analytics endpoints require a Bearer JWT obtained from POST /v1/auth/login.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
