// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Creates a new organisation, provisions a default app, generates an API key (pk_live_*) and returns a signed JWT. This is the entry point for all new tenants.",
                "tags": ["auth"],
                "summary": "Register a new organisation",
                "operationId": "register",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/RegisterRequest"}
                    }
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/RegisterResponse"}},
                    "400": {"description": "Bad Request",    "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "409": {"description": "Org already exists", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/auth/token": {
            "post": {
                "description": "Exchanges a valid API key for a signed JWT. The JWT is used as a Bearer token in all Query API and Notification Service requests. Tokens expire per the PULSE_AUTH_JWT_EXPIRY config (default 24h).",
                "tags": ["auth"],
                "summary": "Exchange API key for JWT",
                "operationId": "token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/TokenRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/TokenResponse"}},
                    "401": {"description": "Invalid key", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/auth/refresh": {
            "post": {
                "description": "Issues a fresh JWT without re-supplying the API key. Requires a valid (non-expired) Bearer token in the Authorization header. Used by dashboard clients to silently renew sessions.",
                "tags": ["auth"],
                "summary": "Refresh JWT",
                "operationId": "refresh",
                "produces": ["application/json"],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer <current_jwt>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {"description": "OK",             "schema": {"$ref": "#/definitions/TokenResponse"}},
                    "401": {"description": "Token expired or invalid", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/auth/validate": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Introspects the supplied JWT and returns the decoded claims. Primarily used by internal services for token validation. The Query API verifies tokens locally (stateless) and does NOT call this endpoint on every request.",
                "tags": ["auth"],
                "summary": "Validate JWT and return claims",
                "operationId": "validate",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK",             "schema": {"$ref": "#/definitions/ValidateResponse"}},
                    "401": {"description": "Token invalid",  "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/auth/apikey/rotate": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Generates a new API key for the specified app and invalidates the previous one. Active JWTs remain valid until they expire (see PULSE_AUTH_JWT_EXPIRY). New SDK clients must use the new key immediately.",
                "tags": ["auth"],
                "summary": "Rotate API key",
                "operationId": "rotateAPIKey",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/RotateKeyRequest"}
                    }
                ],
                "responses": {
                    "200": {"description": "OK",          "schema": {"$ref": "#/definitions/RotateKeyResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized","schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "App not found","schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "example": "ok"},
                "service": {"type": "string", "example": "authservice"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string", "example": "invalid api key"}
            }
        },
        "RegisterRequest": {
            "type": "object",
            "required": ["org_name", "email"],
            "properties": {
                "org_name":  {"type": "string", "example": "Acme Corp"},
                "app_name":  {"type": "string", "example": "Acme iOS", "description": "Optional; defaults to org_name + ' Default App'"},
                "email":     {"type": "string", "format": "email", "example": "admin@acme.io"}
            }
        },
        "RegisterResponse": {
            "type": "object",
            "properties": {
                "org_id":   {"type": "string", "example": "org_7f3k2m"},
                "app_id":   {"type": "string", "example": "app_abc123"},
                "api_key":  {"type": "string", "example": "pk_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                             "description": "Pass this in the X-API-Key header for all ingest requests"},
                "token":    {"type": "string", "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."},
                "expires":  {"type": "string", "format": "date-time", "example": "2026-04-13T12:00:00Z"}
            }
        },
        "TokenRequest": {
            "type": "object",
            "required": ["api_key"],
            "properties": {
                "api_key": {"type": "string", "example": "pk_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
            }
        },
        "TokenResponse": {
            "type": "object",
            "properties": {
                "token":   {"type": "string", "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."},
                "org_id":  {"type": "string", "example": "org_7f3k2m"},
                "app_id":  {"type": "string", "example": "app_abc123"},
                "expires": {"type": "string", "format": "date-time", "example": "2026-04-13T12:00:00Z"}
            }
        },
        "ValidateResponse": {
            "type": "object",
            "properties": {
                "valid":   {"type": "boolean", "example": true},
                "org_id":  {"type": "string",  "example": "org_7f3k2m"},
                "app_id":  {"type": "string",  "example": "app_abc123"},
                "role":    {"type": "string",  "example": "admin"},
                "expires": {"type": "string",  "format": "date-time", "example": "2026-04-13T12:00:00Z"}
            }
        },
        "RotateKeyRequest": {
            "type": "object",
            "required": ["app_id"],
            "properties": {
                "app_id": {"type": "string", "example": "app_abc123"}
            }
        },
        "RotateKeyResponse": {
            "type": "object",
            "properties": {
                "app_id":  {"type": "string", "example": "app_abc123"},
                "api_key": {"type": "string", "example": "pk_live_yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            "description": "New API key; previous key is immediately invalidated"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT bearer token. Obtain from POST /v1/auth/token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {"name": "auth",   "description": "Token issuance, refresh, validation, and API key rotation"},
        {"name": "system", "description": "Health and operational checks"}
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "PulseAnalytics — Auth Service API",
	Description:      "Token issuance and API key management service. Issues HS256 JWTs consumed by the Query API and Notification Service. The Query API verifies tokens locally — it does NOT make a network call to this service on every request.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
