// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
//
// NOTE: The Funnel Processor has NO HTTP business API.
// It is a stateful Kafka consumer that evaluates funnel definitions in real-time.
// This file documents its Kafka message schemas and Redis state contracts
// for internal developer reference.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK",       "schema": {"$ref": "#/definitions/HealthResponse"}},
                    "503": {"description": "Degraded", "schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },
        "/metrics": {
            "get": {
                "tags": ["system"],
                "summary": "Prometheus metrics",
                "operationId": "metrics",
                "description": "Key metrics: funnel_processor_conversions_total, funnel_processor_active_funnels, funnel_processor_redis_zset_size, funnel_processor_kafka_consumer_lag.",
                "produces": ["text/plain"],
                "responses": {
                    "200": {"description": "Prometheus text format metrics"}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "enum": ["ok","degraded"], "example": "ok"},
                "service": {"type": "string", "example": "funnel"}
            }
        },
        "FunnelDefinition": {
            "description": "Loaded from PostgreSQL on startup (30-second hot-reload). Cached in-memory per pod.",
            "type": "object",
            "properties": {
                "funnel_id":      {"type": "string",  "example": "f-1712345678000000000"},
                "app_id":         {"type": "string",  "example": "app_abc123"},
                "name":           {"type": "string",  "example": "Onboarding Funnel"},
                "steps":          {"type": "array",   "items": {"type": "string"},
                                   "example": ["app_installed","user_registered","purchase_completed"]},
                "window_seconds": {"type": "integer", "format": "int64", "example": 604800,
                                   "description": "Max time between first step and last step for a valid conversion"}
            }
        },
        "ConversionEvent": {
            "description": "Produced to Kafka topic: agg-results when a user completes all funnel steps within the window.",
            "type": "object",
            "properties": {
                "funnel_id":       {"type": "string",  "example": "f-1712345678000000000"},
                "app_id":          {"type": "string",  "example": "app_abc123"},
                "user_id":         {"type": "string",  "example": "usr_xyz"},
                "device_id":       {"type": "string",  "example": "d1e2f3g4-h5i6-j7k8"},
                "steps_completed": {"type": "integer", "example": 3,
                                    "description": "Number of steps completed (equal to total steps for full conversion)"},
                "total_steps":     {"type": "integer", "example": 3},
                "converted":       {"type": "boolean", "example": true},
                "start_time_ms":   {"type": "integer", "format": "int64",
                                    "description": "Timestamp of first step completion"},
                "end_time_ms":     {"type": "integer", "format": "int64",
                                    "description": "Timestamp of last step completion"},
                "duration_s":      {"type": "number",  "format": "double", "example": 43200.0,
                                    "description": "Time from first to last step in seconds"}
            }
        }
    },
    "tags": [
        {
            "name": "system",
            "description": "Health and Prometheus metrics. Funnel Processor has no business HTTP API."
        }
    ],
    "x-kafka-interface": {
        "consumes": [
            {
                "topic": "session-events",
                "consumer_group": "funnel-processor",
                "key": "app_id",
                "value_schema": "SessionEvent (JSON)",
                "partitions": 6,
                "description": "Incoming session events. For each event, checks if it matches a funnel step for the relevant app."
            }
        ],
        "produces": [
            {
                "topic": "agg-results",
                "key": "app_id",
                "value_schema": "ConversionEvent (JSON)",
                "partitions": 4,
                "description": "Emitted when a user completes all steps in a funnel within the conversion window."
            }
        ]
    },
    "x-redis-state": {
        "funnel_progress": {
            "key_pattern": "funnel:{funnel_id}:{user_id}",
            "type": "ZSET",
            "score": "step_index (0-based)",
            "member": "event_timestamp_ms",
            "ttl": "window_seconds (per funnel definition)",
            "description": "Tracks which steps a user has completed. On each new step match, ZADD with score=step_index. Conversion detected when ZCARD == total_steps."
        },
        "memory_estimate": "~1M concurrent funnel evaluations × 500B ≈ 500 MB Redis"
    },
    "x-processing-logic": {
        "funnel_reload_interval": "30 seconds (PostgreSQL hot-reload, cached in-process)",
        "step_matching": "Event name must exactly match the next uncompleted step in the funnel definition",
        "conversion_window": "Enforced via Redis ZSET TTL — if first-step entry expires before all steps are completed, the partial progress is discarded",
        "out_of_order_steps": "Not supported — steps must be completed in declared order",
        "partial_conversions": "Tracked in Redis but not emitted to agg-results (only full conversions are emitted)"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:9094",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "PulseAnalytics — Funnel Processor (Internal)",
	Description:      "Stateful Kafka consumer service. Consumes session-events, loads funnel definitions from PostgreSQL (30s hot-reload), tracks per-user funnel progress in Redis ZSETs, and emits ConversionEvents to agg-results when all steps are completed within the conversion window. No business HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
