// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "description": "Returns service health. A 200 indicates the CH-Writer pod is alive and its Kafka consumer is running. Does NOT indicate ClickHouse connectivity — use /metrics for consumer lag.",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK",      "schema": {"$ref": "#/definitions/HealthResponse"}},
                    "503": {"description": "Unhealthy","schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },
        "/metrics": {
            "get": {
                "tags": ["system"],
                "summary": "Prometheus metrics",
                "operationId": "metrics",
                "description": "Exposes Prometheus-format metrics. Key metrics to watch: chwriter_kafka_consumer_lag (alert if > 100K), chwriter_clickhouse_insert_errors_total, chwriter_rows_written_total, chwriter_batch_flush_duration_seconds.",
                "produces": ["text/plain"],
                "responses": {
                    "200": {"description": "Prometheus text format metrics"}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "enum": ["ok","degraded"], "example": "ok"},
                "service": {"type": "string", "example": "chwriter"}
            }
        }
    },
    "tags": [
        {
            "name": "system",
            "description": "Health and Prometheus metrics. CH-Writer has no business HTTP API — its primary interface is Kafka consumption and ClickHouse writes."
        }
    ],
    "x-internal-kafka-interface": {
        "description": "CH-Writer is a Kafka consumer service. It has no business HTTP API. The following documents its Kafka interface for internal reference.",
        "consumes": [
            {
                "topic": "enriched-events",
                "consumer_group": "chwriter-enriched",
                "key": "app_id:device_id",
                "value_schema": "EnrichedEvent (JSON)",
                "partitions": 12,
                "description": "Primary event stream. Batched into ClickHouse events table in 1s windows or 500K rows."
            },
            {
                "topic": "session-events",
                "consumer_group": "chwriter-session",
                "key": "app_id",
                "value_schema": "SessionEvent (JSON)",
                "partitions": 6,
                "description": "Session start/end events. Written to session_summaries ClickHouse table."
            },
            {
                "topic": "agg-results",
                "consumer_group": "chwriter-agg",
                "key": "app_id",
                "value_schema": "ConversionEvent (JSON)",
                "partitions": 4,
                "description": "Funnel conversion events. Written to funnel_conversions ClickHouse table."
            }
        ],
        "clickhouse_tables": [
            {"table": "events",             "insert_format": "Native (binary)", "batch_size": "500K rows or 1s"},
            {"table": "session_summaries",  "insert_format": "Native (binary)", "batch_size": "500K rows or 1s"},
            {"table": "funnel_conversions", "insert_format": "Native (binary)", "batch_size": "500K rows or 1s"}
        ]
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:9091",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "PulseAnalytics — CH-Writer Internal API",
	Description:      "High-throughput Kafka-to-ClickHouse writer. Consumes enriched-events, session-events, and agg-results topics; buffers rows in 1-second or 500K-row windows; bulk-inserts via ClickHouse Native protocol. Exposes only /health and /metrics — no business HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
