// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
//
// NOTE: The Session Engine has NO HTTP business API.
// It is a stateful Kafka consumer that tracks session state in Redis.
// This file documents its Kafka message schemas and Redis key contracts
// for internal developer reference.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK",       "schema": {"$ref": "#/definitions/HealthResponse"}},
                    "503": {"description": "Degraded", "schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },
        "/metrics": {
            "get": {
                "tags": ["system"],
                "summary": "Prometheus metrics",
                "operationId": "metrics",
                "description": "Key metrics: session_engine_sessions_started_total, session_engine_sessions_ended_total, session_engine_redis_errors_total, session_engine_kafka_consumer_lag.",
                "produces": ["text/plain"],
                "responses": {
                    "200": {"description": "Prometheus text format metrics"}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "enum": ["ok","degraded"], "example": "ok"},
                "service": {"type": "string", "example": "session"}
            }
        },
        "SessionState": {
            "description": "Redis value stored at key session:{app_id}:{device_id} (SETEX, TTL = 30 minutes). Updated on every incoming event.",
            "type": "object",
            "properties": {
                "session_id":    {"type": "string",  "example": "sess_8f3k2z"},
                "app_id":        {"type": "string",  "example": "app_abc123"},
                "user_id":       {"type": "string",  "example": "usr_xyz"},
                "device_id":     {"type": "string",  "example": "d1e2f3g4-h5i6-j7k8"},
                "start_time_ms": {"type": "integer", "format": "int64", "example": 1712345678000},
                "last_event_ms": {"type": "integer", "format": "int64", "example": 1712345900000},
                "event_count":   {"type": "integer", "example": 12},
                "screens":       {"type": "array",   "items": {"type": "string"},
                                  "example": ["HomeScreen","ProductScreen","CartScreen"]},
                "entry_screen":  {"type": "string",  "example": "HomeScreen"},
                "updated_at":    {"type": "string",  "format": "date-time"}
            }
        },
        "SessionEvent": {
            "description": "Produced to Kafka topic: session-events when a session starts or ends.",
            "type": "object",
            "properties": {
                "session_id":    {"type": "string",  "example": "sess_8f3k2z"},
                "app_id":        {"type": "string",  "example": "app_abc123"},
                "user_id":       {"type": "string",  "example": "usr_xyz"},
                "device_id":     {"type": "string",  "example": "d1e2f3g4-h5i6-j7k8"},
                "type":          {"type": "string",  "enum": ["session_start","session_end"],
                                  "example": "session_end"},
                "start_time_ms": {"type": "integer", "format": "int64", "example": 1712345678000},
                "end_time_ms":   {"type": "integer", "format": "int64", "example": 1712345900000,
                                  "description": "Populated only when type=session_end"},
                "duration_s":    {"type": "number",  "format": "double", "example": 222.0,
                                  "description": "Session duration in seconds (end - start)"},
                "event_count":   {"type": "integer", "example": 12},
                "screens":       {"type": "array",   "items": {"type": "string"}},
                "entry_screen":  {"type": "string",  "example": "HomeScreen"},
                "exit_screen":   {"type": "string",  "example": "CartScreen",
                                  "description": "Last screen before session end"},
                "exit_reason":   {"type": "string",  "enum": ["timeout","explicit_end"],
                                  "description": "timeout = 30-min inactivity TTL expired; explicit_end = app background event"}
            }
        }
    },
    "tags": [
        {
            "name": "system",
            "description": "Health and Prometheus metrics. Session Engine has no business HTTP API."
        }
    ],
    "x-kafka-interface": {
        "consumes": [
            {
                "topic": "enriched-events",
                "consumer_group": "session-engine",
                "key": "app_id:device_id",
                "value_schema": "EnrichedEvent (JSON)",
                "partitions": 12,
                "description": "Incoming enriched events. For each event, looks up or creates a session in Redis."
            }
        ],
        "produces": [
            {
                "topic": "session-events",
                "key": "app_id",
                "value_schema": "SessionEvent (JSON)",
                "partitions": 6,
                "description": "Emits session_start when a new session is created, session_end when the Redis TTL expires or an explicit session-end event is received."
            }
        ]
    },
    "x-redis-keys": {
        "session_state": {
            "key_pattern": "session:{app_id}:{device_id}",
            "type": "string (JSON)",
            "ttl": "30 minutes (refreshed on every event)",
            "schema": "SessionState",
            "description": "TTL expiry is treated as session_end. On expiry, the keyspace notification triggers session_end emission."
        }
    },
    "x-session-logic": {
        "new_session_conditions": [
            "No Redis key exists for session:{app_id}:{device_id} → create new session UUID",
            "Last event timestamp gap > 30 minutes → expire old session, start new one"
        ],
        "session_end_trigger": "Redis SETEX TTL expiry (30-min inactivity) or explicit app_backgrounded event",
        "memory_estimate": "~20M concurrent sessions × 500B = ~10 GB Redis (20% of 100M DAU active simultaneously)"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:9093",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "PulseAnalytics — Session Engine (Internal)",
	Description:      "Stateful Kafka consumer service. Consumes enriched-events, tracks per-device session state in Redis (SETEX with 30-min TTL), and emits session_start / session_end events to the session-events topic. A session ends when the Redis key expires (inactivity timeout) or an explicit app_backgrounded event is received. No business HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
