// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": ["application/json"],
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/events": {
            "post": {
                "security": [{"ApiKeyAuth": []}],
                "description": "Accepts a batch of up to 500 analytics events from SDK clients. Returns 202 immediately after publishing to Kafka — does not wait for downstream processing.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["ingest"],
                "summary": "Ingest event batch",
                "operationId": "ingestEvents",
                "parameters": [
                    {
                        "description": "Event batch payload",
                        "name": "batch",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EventBatch"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Optional: gzip to compress the body",
                        "name": "Content-Encoding",
                        "in": "header"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/IngestResponse"
                        }
                    },
                    "400": {"description": "Bad Request",    "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized",   "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "429": {"description": "Too Many Requests", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/track": {
            "post": {
                "security": [{"ApiKeyAuth": []}],
                "description": "Single-event shorthand. Equivalent to /v1/events with a one-event batch.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["ingest"],
                "summary": "Track a single event",
                "operationId": "trackEvent",
                "parameters": [
                    {
                        "description": "Single event",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/Event"}
                    }
                ],
                "responses": {
                    "202": {"description": "Accepted"},
                    "400": {"description": "Bad Request",  "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/v1/identify": {
            "post": {
                "security": [{"ApiKeyAuth": []}],
                "description": "Updates user profile traits. Triggers a user_updated event and upserts the user document in MongoDB.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["ingest"],
                "summary": "Identify / update user profile",
                "operationId": "identifyUser",
                "parameters": [
                    {
                        "description": "User identity payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/IdentifyRequest"}
                    }
                ],
                "responses": {
                    "202": {"description": "Accepted"},
                    "400": {"description": "Bad Request",  "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "example": "ok"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string", "example": "invalid api key"}
            }
        },
        "IngestResponse": {
            "type": "object",
            "properties": {
                "accepted": {"type": "integer", "example": 42,  "description": "Number of new events accepted"},
                "filtered": {"type": "integer", "example": 3,   "description": "Duplicates filtered"}
            }
        },
        "EventBatch": {
            "type": "object",
            "required": ["app_id", "device_id", "events"],
            "properties": {
                "app_id":      {"type": "string",  "example": "app_abc123"},
                "device_id":   {"type": "string",  "example": "d1e2f3g4-h5i6-j7k8"},
                "user_id":     {"type": "string",  "example": "usr_xyz"},
                "sdk_version": {"type": "string",  "example": "2.1.0"},
                "sent_at_ms":  {"type": "integer", "format": "int64", "example": 1712345678000},
                "events": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/Event"},
                    "maxItems": 500
                }
            }
        },
        "Event": {
            "type": "object",
            "required": ["event_name"],
            "properties": {
                "event_id":   {"type": "string",  "example": "550e8400-e29b-41d4-a716-446655440000"},
                "event_name": {"type": "string",  "example": "purchase_completed"},
                "event_time": {"type": "integer", "format": "int64", "example": 1712345678000, "description": "Client-side epoch ms"},
                "props":      {"type": "object",  "additionalProperties": true, "example": {"item_id": "sku_999", "price": 29.99}},
                "revenue":    {"type": "number",  "format": "double", "example": 29.99},
                "device":     {"$ref": "#/definitions/DeviceContext"},
                "app":        {"$ref": "#/definitions/AppContext"}
            }
        },
        "DeviceContext": {
            "type": "object",
            "properties": {
                "device_model":  {"type": "string", "example": "iPhone 15 Pro"},
                "os":            {"type": "string", "example": "iOS"},
                "os_version":    {"type": "string", "example": "17.4"},
                "manufacturer":  {"type": "string", "example": "Apple"},
                "network_type":  {"type": "string", "example": "wifi"},
                "language":      {"type": "string", "example": "en-US"},
                "timezone":      {"type": "string", "example": "America/New_York"},
                "user_agent":    {"type": "string", "example": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4)"}
            }
        },
        "AppContext": {
            "type": "object",
            "properties": {
                "version":     {"type": "string", "example": "4.2.1"},
                "build":       {"type": "string", "example": "2024050100"},
                "platform":    {"type": "string", "enum": ["android","ios","web","react_native","flutter","server"]},
                "environment": {"type": "string", "enum": ["production","development"]}
            }
        },
        "IdentifyRequest": {
            "type": "object",
            "required": ["user_id"],
            "properties": {
                "user_id": {"type": "string", "example": "usr_xyz"},
                "traits": {
                    "type": "object",
                    "additionalProperties": true,
                    "example": {"email": "alice@example.com", "plan": "pro"}
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key issued per app. Pass in the X-API-Key header.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    },
    "tags": [
        {"name": "ingest",  "description": "Event ingestion endpoints"},
        {"name": "system",  "description": "Health and readiness checks"}
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "PulseAnalytics — Ingest Gateway API",
	Description:      "High-throughput event ingestion API. Accepts batches of up to 500 events per request at up to 100M events/second across the cluster.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
