// Code generated by swaggo/swag. DO NOT EDIT.
// Re-generate with: make swagger
//
// NOTE: The Enricher Service has NO HTTP business API.
// It is a pure Kafka consumer/producer service.
// This file documents its Kafka message interface and internal
// processing contract for internal developer reference.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PulseAnalytics Support",
            "url": "https://pulse-analytics.io/support",
            "email": "support@pulse-analytics.io"
        },
        "license": {"name": "MIT"},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "tags": ["system"],
                "summary": "Health check",
                "operationId": "health",
                "description": "Returns service liveness. A 200 confirms the Enricher pod is alive and Kafka consumer group lag is being updated.",
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "OK",       "schema": {"$ref": "#/definitions/HealthResponse"}},
                    "503": {"description": "Degraded", "schema": {"$ref": "#/definitions/HealthResponse"}}
                }
            }
        },
        "/metrics": {
            "get": {
                "tags": ["system"],
                "summary": "Prometheus metrics",
                "operationId": "metrics",
                "description": "Key metrics: enricher_kafka_consumer_lag, enricher_events_enriched_total, enricher_ua_parse_errors_total, enricher_geoip_misses_total, enricher_clock_skew_corrections_total.",
                "produces": ["text/plain"],
                "responses": {
                    "200": {"description": "Prometheus text format metrics"}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status":  {"type": "string", "enum": ["ok","degraded"], "example": "ok"},
                "service": {"type": "string", "example": "enricher"}
            }
        },
        "RawEvent": {
            "description": "Consumed from Kafka topic: raw-events. Produced by the Gateway Service.",
            "type": "object",
            "properties": {
                "event_id":   {"type": "string",  "example": "550e8400-e29b-41d4-a716-446655440000"},
                "event_name": {"type": "string",  "example": "purchase_completed"},
                "event_time": {"type": "integer", "format": "int64", "example": 1712345678000,
                               "description": "Client-side epoch ms. May have clock skew."},
                "app_id":     {"type": "string",  "example": "app_abc123"},
                "device_id":  {"type": "string",  "example": "d1e2f3g4-h5i6-j7k8"},
                "user_id":    {"type": "string",  "example": "usr_xyz"},
                "props":      {"type": "object",  "additionalProperties": true},
                "revenue":    {"type": "number",  "format": "double"},
                "device": {
                    "type": "object",
                    "properties": {
                        "device_model": {"type": "string"},
                        "os":           {"type": "string"},
                        "os_version":   {"type": "string"},
                        "network_type": {"type": "string"},
                        "language":     {"type": "string"},
                        "timezone":     {"type": "string"},
                        "user_agent":   {"type": "string", "example": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4)"}
                    }
                },
                "app": {
                    "type": "object",
                    "properties": {
                        "version":     {"type": "string"},
                        "build":       {"type": "string"},
                        "platform":    {"type": "string", "enum": ["android","ios","web","react_native","flutter","server"]},
                        "environment": {"type": "string", "enum": ["production","development"]}
                    }
                },
                "server_time": {"type": "integer", "format": "int64",
                                "description": "Gateway server timestamp (ms). Added by Gateway before Kafka publish."}
            }
        },
        "EnrichedEvent": {
            "description": "Produced to Kafka topic: enriched-events. Consumed by CH-Writer and Session Engine.",
            "type": "object",
            "properties": {
                "event_id":          {"type": "string"},
                "event_name":        {"type": "string"},
                "app_id":            {"type": "string"},
                "device_id":         {"type": "string"},
                "user_id":           {"type": "string"},
                "session_id":        {"type": "string", "description": "Assigned by Session Engine; empty until session lookup completes"},
                "server_time":       {"type": "integer", "format": "int64", "description": "Authoritative timestamp (ms)"},
                "client_offset_ms":  {"type": "integer", "format": "int64",
                                      "description": "Difference between server_time and event_time. Non-zero indicates clock skew correction."},
                "props":             {"type": "object", "additionalProperties": true},
                "revenue":           {"type": "number", "format": "double"},
                "country_code":      {"type": "string", "example": "US"},
                "country_name":      {"type": "string", "example": "United States"},
                "region":            {"type": "string", "example": "California"},
                "city":              {"type": "string", "example": "San Francisco"},
                "latitude":          {"type": "number", "format": "double"},
                "longitude":         {"type": "number", "format": "double"},
                "browser":           {"type": "string", "example": "Chrome"},
                "browser_version":   {"type": "string", "example": "123.0"},
                "os_family":         {"type": "string", "example": "iOS"},
                "device_type":       {"type": "string", "enum": ["mobile","tablet","desktop","bot"]},
                "install_source":    {"type": "string", "example": "google",
                                      "description": "utm_source from first-touch install event"},
                "campaign_id":       {"type": "string"},
                "adset_id":          {"type": "string"}
            }
        },
        "DLQEvent": {
            "description": "Produced to Kafka topic: dlq-events on unrecoverable parse error.",
            "type": "object",
            "properties": {
                "raw_payload":  {"type": "string", "description": "Base64-encoded original raw event bytes"},
                "error":        {"type": "string", "example": "invalid UTF-8 in props field"},
                "failed_at_ms": {"type": "integer","format": "int64"}
            }
        }
    },
    "tags": [
        {
            "name": "system",
            "description": "Health and Prometheus metrics. Enricher has no business HTTP API — its interface is Kafka."
        }
    ],
    "x-kafka-interface": {
        "consumes": [
            {
                "topic": "raw-events",
                "consumer_group": "enricher",
                "key": "app_id:device_id",
                "value_schema": "RawEvent (JSON)",
                "partitions": 12,
                "parallelism": "50 workers per pod",
                "description": "Raw events from Gateway. Each worker independently enriches events."
            }
        ],
        "produces": [
            {
                "topic": "enriched-events",
                "key": "app_id:device_id",
                "value_schema": "EnrichedEvent (JSON)",
                "description": "Successfully enriched events forwarded to Session Engine and CH-Writer."
            },
            {
                "topic": "dlq-events",
                "key": "app_id",
                "value_schema": "DLQEvent (JSON)",
                "description": "Events that failed enrichment due to unrecoverable parse errors."
            }
        ],
        "enrichment_steps": [
            "1. Parse User-Agent string → browser, browser_version, os_family, device_type",
            "2. GeoIP lookup via MaxMind GeoLite2 mmdb (in-process, ~1µs) → country, region, city, lat/lon",
            "3. Clock skew correction: if |server_time - event_time| > 5 min → set server_time as authoritative, record client_offset_ms",
            "4. Delegate session ID assignment to Session Engine via Redis lookup",
            "5. Propagate first-touch attribution fields (install_source, campaign_id, adset_id) from user profile"
        ]
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:9092",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "PulseAnalytics — Enricher Service (Internal)",
	Description:      "Kafka consumer service. Consumes raw-events (12 partitions), enriches each event with GeoIP, User-Agent parsing, server-side timestamp correction, and session ID assignment, then produces to enriched-events. Unrecoverable parse failures go to dlq-events. No business HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
